# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'camera.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Camera(object):
    def setupUi(self, Camera):
        Camera.setObjectName("Camera")
        Camera.resize(400, 450)
        self.verticalLayout = QtWidgets.QVBoxLayout(Camera)
        self.verticalLayout.setObjectName("verticalLayout")
        self.VideoLabel = QtWidgets.QLabel(Camera)
        self.VideoLabel.setText("")
        self.VideoLabel.setObjectName("VideoLabel")
        self.verticalLayout.addWidget(self.VideoLabel)

        self.retranslateUi(Camera)
        QtCore.QMetaObject.connectSlotsByName(Camera)

    def retranslateUi(self, Camera):
        _translate = QtCore.QCoreApplication.translate
        Camera.setWindowTitle(_translate("Camera", "Form"))
