# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'operation.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Operation(object):
    def setupUi(self, Operation):
        Operation.setObjectName("Operation")
        Operation.resize(1215, 794)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Operation)
        self.horizontalLayout.setContentsMargins(-1, -1, 9, -1)
        self.horizontalLayout.setSpacing(11)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget_left = QtWidgets.QWidget(Operation)
        self.widget_left.setStyleSheet("background-color: rgb(218, 218, 218);\n"
"border-radius: 5px;\n"
"")
        self.widget_left.setObjectName("widget_left")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget_left)
        self.verticalLayout_3.setContentsMargins(9, 9, 9, 9)
        self.verticalLayout_3.setSpacing(9)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.scrollArea = QtWidgets.QScrollArea(self.widget_left)
        self.scrollArea.setStyleSheet("/*QScrollArea{\n"
"    background-color: rgb(243, 243, 243);\n"
"    border:None;\n"
"}*/\n"
"\n"
"QScrollBar:vertical {\n"
"    border-radius: 5px; \n"
"    background: #f0f0f0;        \n"
"    width: 5px;                \n"
"    margin: 22px 5px 22px 5px;     \n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"    background: #c0c0c0;         \n"
"    min-height: 30px;          \n"
"    border-radius: 5px;         \n"
"}\n"
"\n"
"QScrollBar::add-line:vertical, QScrollBar::sub-line:vertical {\n"
"    background: none;        \n"
"}\n"
"\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: none;     \n"
"}")
        self.scrollArea.setLineWidth(0)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 427, 758))
        self.scrollAreaWidgetContents.setStyleSheet("")
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_4.setContentsMargins(0, 0, 9, 0)
        self.verticalLayout_4.setSpacing(11)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.radar_panel = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.radar_panel.setStyleSheet("background-color: rgb(236, 240, 241);")
        self.radar_panel.setObjectName("radar_panel")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout(self.radar_panel)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.widget_21 = QtWidgets.QWidget(self.radar_panel)
        self.widget_21.setObjectName("widget_21")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_21)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_radar = QtWidgets.QLabel(self.widget_21)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_radar.sizePolicy().hasHeightForWidth())
        self.label_radar.setSizePolicy(sizePolicy)
        self.label_radar.setStyleSheet("font: 13pt \"Arial\";")
        self.label_radar.setObjectName("label_radar")
        self.horizontalLayout_2.addWidget(self.label_radar)
        self.radar_control_button = QtWidgets.QPushButton(self.widget_21)
        self.radar_control_button.setMinimumSize(QtCore.QSize(0, 30))
        self.radar_control_button.setStyleSheet("QPushButton {\n"
"    background-color: rgb(39, 174, 96);\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 7px;\n"
"    border: 2px groove gray;\n"
"    border-style: outset;\n"
"    font: 75 9pt \"Arial\";\n"
"}\n"
"QPushButton:disabled {\n"
"    background-color:gray;\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 7px;\n"
"    border: 2px groove gray;\n"
"    border-style: outset;\n"
"    font: 75 9pt \"Arial\";\n"
"}\n"
"")
        self.radar_control_button.setCheckable(True)
        self.radar_control_button.setObjectName("radar_control_button")
        self.horizontalLayout_2.addWidget(self.radar_control_button)
        self.horizontalLayout_19.addWidget(self.widget_21)
        self.verticalLayout_4.addWidget(self.radar_panel)
        self.camera_3d_panel = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.camera_3d_panel.setStyleSheet("background-color: rgb(236, 240, 241);")
        self.camera_3d_panel.setObjectName("camera_3d_panel")
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout(self.camera_3d_panel)
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.widget_25 = QtWidgets.QWidget(self.camera_3d_panel)
        self.widget_25.setObjectName("widget_25")
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout(self.widget_25)
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        self.label_4 = QtWidgets.QLabel(self.widget_25)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_28.addWidget(self.label_4)
        self.camera_3d_button = QtWidgets.QPushButton(self.widget_25)
        self.camera_3d_button.setEnabled(True)
        self.camera_3d_button.setMinimumSize(QtCore.QSize(0, 30))
        self.camera_3d_button.setStyleSheet("QPushButton {\n"
"    background-color:rgb(41, 128, 185);\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 10px;\n"
"    border: 2px groove gray;\n"
"    border-style: outset;\n"
"    font: 75 9pt \"Arial\";\n"
"}\n"
"QPushButton:disabled {\n"
"    background-color:gray;\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 7px;\n"
"    border: 2px groove gray;\n"
"    border-style: outset;\n"
"    font: 75 9pt \"Arial\";\n"
"}\n"
"")
        self.camera_3d_button.setObjectName("camera_3d_button")
        self.horizontalLayout_28.addWidget(self.camera_3d_button)
        self.horizontalLayout_27.addWidget(self.widget_25)
        self.verticalLayout_4.addWidget(self.camera_3d_panel)
        self.basic_control_panel = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.basic_control_panel.setStyleSheet("background-color: rgb(236, 240, 241);")
        self.basic_control_panel.setObjectName("basic_control_panel")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.basic_control_panel)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.widget_17 = QtWidgets.QWidget(self.basic_control_panel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_17.sizePolicy().hasHeightForWidth())
        self.widget_17.setSizePolicy(sizePolicy)
        self.widget_17.setObjectName("widget_17")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget_17)
        self.horizontalLayout_4.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.basic_control = QtWidgets.QLabel(self.widget_17)
        self.basic_control.setStyleSheet("font: 13pt \"Arial\";")
        self.basic_control.setObjectName("basic_control")
        self.horizontalLayout_4.addWidget(self.basic_control)
        self.basic_control_selection = QtWidgets.QComboBox(self.widget_17)
        self.basic_control_selection.setMinimumSize(QtCore.QSize(0, 25))
        self.basic_control_selection.setStyleSheet("color:black;")
        self.basic_control_selection.setObjectName("basic_control_selection")
        self.basic_control_selection.addItem("")
        self.basic_control_selection.addItem("")
        self.basic_control_selection.addItem("")
        self.horizontalLayout_4.addWidget(self.basic_control_selection)
        self.verticalLayout_5.addWidget(self.widget_17)
        self.widget_8 = QtWidgets.QWidget(self.basic_control_panel)
        self.widget_8.setStyleSheet("")
        self.widget_8.setObjectName("widget_8")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.widget_8)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.basic_control_button = QtWidgets.QPushButton(self.widget_8)
        self.basic_control_button.setMinimumSize(QtCore.QSize(0, 30))
        self.basic_control_button.setStyleSheet("QPushButton {\n"
"    background-color: rgb(39, 174, 96);\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 7px;\n"
"    border: 2px groove gray;\n"
"    border-style: outset;\n"
"    font: 75 9pt \"Arial\";\n"
"}\n"
"QPushButton:disabled {\n"
"    background-color:gray;\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 7px;\n"
"    border: 2px groove gray;\n"
"    border-style: outset;\n"
"    font: 75 9pt \"Arial\";\n"
"}\n"
"")
        self.basic_control_button.setCheckable(True)
        self.basic_control_button.setObjectName("basic_control_button")
        self.horizontalLayout_13.addWidget(self.basic_control_button)
        self.verticalLayout_5.addWidget(self.widget_8)
        self.verticalLayout_4.addWidget(self.basic_control_panel)
        self.map_navigation_panel = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.map_navigation_panel.setStyleSheet("background-color: rgb(236, 240, 241);")
        self.map_navigation_panel.setObjectName("map_navigation_panel")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.map_navigation_panel)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget_9 = QtWidgets.QWidget(self.map_navigation_panel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_9.sizePolicy().hasHeightForWidth())
        self.widget_9.setSizePolicy(sizePolicy)
        self.widget_9.setObjectName("widget_9")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget_9)
        self.horizontalLayout_5.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_3 = QtWidgets.QLabel(self.widget_9)
        self.label_3.setStyleSheet("font: 13pt \"Arial\";")
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_5.addWidget(self.label_3)
        self.navigation_selection = QtWidgets.QComboBox(self.widget_9)
        self.navigation_selection.setStyleSheet("color:black;")
        self.navigation_selection.setObjectName("navigation_selection")
        self.navigation_selection.addItem("")
        self.navigation_selection.addItem("")
        self.horizontalLayout_5.addWidget(self.navigation_selection)
        self.verticalLayout.addWidget(self.widget_9)
        self.widget_2 = QtWidgets.QWidget(self.map_navigation_panel)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.navigation_2d_button = QtWidgets.QPushButton(self.widget_2)
        self.navigation_2d_button.setMinimumSize(QtCore.QSize(0, 30))
        self.navigation_2d_button.setStyleSheet("QPushButton {\n"
"    background-color:rgb(41, 128, 185);\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 10px;\n"
"    border: 2px groove gray;\n"
"    border-style: outset;\n"
"    font: 75 9pt \"Arial\";\n"
"}\n"
"QPushButton:disabled {\n"
"    background-color:gray;\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 7px;\n"
"    border: 2px groove gray;\n"
"    border-style: outset;\n"
"    font: 75 9pt \"Arial\";\n"
"}\n"
"")
        self.navigation_2d_button.setCheckable(True)
        self.navigation_2d_button.setObjectName("navigation_2d_button")
        self.horizontalLayout_8.addWidget(self.navigation_2d_button)
        self.navigation_3d_button = QtWidgets.QPushButton(self.widget_2)
        self.navigation_3d_button.setMinimumSize(QtCore.QSize(0, 30))
        self.navigation_3d_button.setStyleSheet("QPushButton {\n"
"    background-color:rgb(41, 128, 185);\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 10px;\n"
"    border: 2px groove gray;\n"
"    border-style: outset;\n"
"    font: 75 9pt \"Arial\";\n"
"}\n"
"QPushButton:disabled {\n"
"    background-color:gray;\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 7px;\n"
"    border: 2px groove gray;\n"
"    border-style: outset;\n"
"    font: 75 9pt \"Arial\";\n"
"}\n"
"")
        self.navigation_3d_button.setCheckable(True)
        self.navigation_3d_button.setObjectName("navigation_3d_button")
        self.horizontalLayout_8.addWidget(self.navigation_3d_button)
        self.verticalLayout.addWidget(self.widget_2)
        self.verticalLayout_4.addWidget(self.map_navigation_panel)
        self.slam_mapping_panel = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.slam_mapping_panel.setStyleSheet("background-color: rgb(236, 240, 241);")
        self.slam_mapping_panel.setObjectName("slam_mapping_panel")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.slam_mapping_panel)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget_20 = QtWidgets.QWidget(self.slam_mapping_panel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_20.sizePolicy().hasHeightForWidth())
        self.widget_20.setSizePolicy(sizePolicy)
        self.widget_20.setObjectName("widget_20")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.widget_20)
        self.horizontalLayout_17.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_map_nav = QtWidgets.QLabel(self.widget_20)
        self.label_map_nav.setStyleSheet("font: 13pt \"Arial\";")
        self.label_map_nav.setObjectName("label_map_nav")
        self.horizontalLayout_17.addWidget(self.label_map_nav)
        self.build_map_selection = QtWidgets.QComboBox(self.widget_20)
        self.build_map_selection.setMinimumSize(QtCore.QSize(0, 25))
        self.build_map_selection.setStyleSheet("color:black;")
        self.build_map_selection.setObjectName("build_map_selection")
        self.build_map_selection.addItem("")
        self.build_map_selection.addItem("")
        self.horizontalLayout_17.addWidget(self.build_map_selection)
        self.verticalLayout_2.addWidget(self.widget_20)
        self.widget_10 = QtWidgets.QWidget(self.slam_mapping_panel)
        self.widget_10.setStyleSheet("")
        self.widget_10.setObjectName("widget_10")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.widget_10)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.open_build_map = QtWidgets.QPushButton(self.widget_10)
        self.open_build_map.setMinimumSize(QtCore.QSize(0, 30))
        self.open_build_map.setStyleSheet("QPushButton {\n"
"    background-color:rgb(41, 128, 185);\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 10px;\n"
"    border: 2px groove gray;\n"
"    border-style: outset;\n"
"    font: 75 9pt \"Arial\";\n"
"}\n"
"QPushButton:disabled {\n"
"    background-color:gray;\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 7px;\n"
"    border: 2px groove gray;\n"
"    border-style: outset;\n"
"    font: 75 9pt \"Arial\";\n"
"}\n"
"")
        self.open_build_map.setCheckable(True)
        self.open_build_map.setObjectName("open_build_map")
        self.horizontalLayout_6.addWidget(self.open_build_map)
        self.save_mapping_button = QtWidgets.QPushButton(self.widget_10)
        self.save_mapping_button.setMinimumSize(QtCore.QSize(0, 30))
        self.save_mapping_button.setStyleSheet("QPushButton {\n"
"    background-color: rgb(39, 174, 96);\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 7px;\n"
"    border: 2px groove gray;\n"
"    border-style: outset;\n"
"    font: 75 9pt \"Arial\";\n"
"}\n"
"QPushButton:disabled {\n"
"    background-color:gray;\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 7px;\n"
"    border: 2px groove gray;\n"
"    border-style: outset;\n"
"    font: 75 9pt \"Arial\";\n"
"}\n"
"")
        self.save_mapping_button.setObjectName("save_mapping_button")
        self.horizontalLayout_6.addWidget(self.save_mapping_button)
        self.verticalLayout_2.addWidget(self.widget_10)
        self.verticalLayout_4.addWidget(self.slam_mapping_panel)
        self.led_control_panel = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.led_control_panel.setStyleSheet("background-color: rgb(236, 240, 241);")
        self.led_control_panel.setObjectName("led_control_panel")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.led_control_panel)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_10 = QtWidgets.QLabel(self.led_control_panel)
        self.label_10.setStyleSheet("font: 13pt \"Arial\";")
        self.label_10.setObjectName("label_10")
        self.verticalLayout_9.addWidget(self.label_10)
        self.widget_16 = QtWidgets.QWidget(self.led_control_panel)
        self.widget_16.setObjectName("widget_16")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.widget_16)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.horizontalLayout_palette = QtWidgets.QHBoxLayout()
        self.horizontalLayout_palette.setSpacing(11)
        self.horizontalLayout_palette.setObjectName("horizontalLayout_palette")
        self.widget_15 = QtWidgets.QWidget(self.widget_16)
        self.widget_15.setObjectName("widget_15")
        self.gridLayout = QtWidgets.QGridLayout(self.widget_15)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.lineEdit_HEX = QtWidgets.QLabel(self.widget_15)
        self.lineEdit_HEX.setStyleSheet("")
        self.lineEdit_HEX.setText("")
        self.lineEdit_HEX.setObjectName("lineEdit_HEX")
        self.gridLayout.addWidget(self.lineEdit_HEX, 0, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.widget_15)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 0, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.widget_15)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 1, 0, 1, 1)
        self.lineEdit_RGB = QtWidgets.QLabel(self.widget_15)
        self.lineEdit_RGB.setStyleSheet("")
        self.lineEdit_RGB.setText("")
        self.lineEdit_RGB.setObjectName("lineEdit_RGB")
        self.gridLayout.addWidget(self.lineEdit_RGB, 1, 1, 1, 1)
        self.gridLayout.setColumnStretch(1, 1)
        self.horizontalLayout_palette.addWidget(self.widget_15)
        self.verticalLayout_10.addLayout(self.horizontalLayout_palette)
        self.widget_19 = QtWidgets.QWidget(self.widget_16)
        self.widget_19.setObjectName("widget_19")
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout(self.widget_19)
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.label_luminance = QtWidgets.QLabel(self.widget_19)
        self.label_luminance.setStyleSheet("font: 10pt \"Arial\";")
        self.label_luminance.setObjectName("label_luminance")
        self.horizontalLayout_26.addWidget(self.label_luminance)
        self.color_brightness_slider = QtWidgets.QSlider(self.widget_19)
        self.color_brightness_slider.setOrientation(QtCore.Qt.Horizontal)
        self.color_brightness_slider.setObjectName("color_brightness_slider")
        self.horizontalLayout_26.addWidget(self.color_brightness_slider)
        self.label_value = QtWidgets.QLabel(self.widget_19)
        self.label_value.setObjectName("label_value")
        self.horizontalLayout_26.addWidget(self.label_value)
        self.verticalLayout_10.addWidget(self.widget_19)
        self.verticalLayout_9.addWidget(self.widget_16)
        self.verticalLayout_4.addWidget(self.led_control_panel)
        self.functional_testing_panel = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.functional_testing_panel.setStyleSheet("background-color: rgb(236, 240, 241);")
        self.functional_testing_panel.setObjectName("functional_testing_panel")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.functional_testing_panel)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.widget_12 = QtWidgets.QWidget(self.functional_testing_panel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_12.sizePolicy().hasHeightForWidth())
        self.widget_12.setSizePolicy(sizePolicy)
        self.widget_12.setObjectName("widget_12")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.widget_12)
        self.horizontalLayout_9.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_2 = QtWidgets.QLabel(self.widget_12)
        self.label_2.setStyleSheet("font: 13pt \"Arial\";")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_9.addWidget(self.label_2)
        self.functional_selection = QtWidgets.QComboBox(self.widget_12)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.functional_selection.sizePolicy().hasHeightForWidth())
        self.functional_selection.setSizePolicy(sizePolicy)
        self.functional_selection.setStyleSheet("\\\\ color:black;\n"
"\\\\ border:1px solid black;\n"
"\\\\ border-radius: 5px;")
        self.functional_selection.setObjectName("functional_selection")
        self.horizontalLayout_9.addWidget(self.functional_selection)
        self.verticalLayout_11.addWidget(self.widget_12)
        self.widget_24 = QtWidgets.QWidget(self.functional_testing_panel)
        self.widget_24.setStyleSheet("background-color: rgb(236, 240, 241);")
        self.widget_24.setObjectName("widget_24")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.widget_24)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.restore_btn = QtWidgets.QPushButton(self.widget_24)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.restore_btn.sizePolicy().hasHeightForWidth())
        self.restore_btn.setSizePolicy(sizePolicy)
        self.restore_btn.setMinimumSize(QtCore.QSize(0, 25))
        self.restore_btn.setStyleSheet("QPushButton {\n"
"    background-color: rgb(39, 174, 96);\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 7px;\n"
"    border: 2px groove gray;\n"
"    border-style: outset;\n"
"    font: 75 9pt \"Arial\";\n"
"}\n"
"QPushButton:disabled {\n"
"    background-color:gray;\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 7px;\n"
"    border: 2px groove gray;\n"
"    border-style: outset;\n"
"    font: 75 9pt \"Arial\";\n"
"}\n"
"")
        self.restore_btn.setObjectName("restore_btn")
        self.horizontalLayout_10.addWidget(self.restore_btn)
        self.start_detection_btn = QtWidgets.QPushButton(self.widget_24)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(30)
        sizePolicy.setHeightForWidth(self.start_detection_btn.sizePolicy().hasHeightForWidth())
        self.start_detection_btn.setSizePolicy(sizePolicy)
        self.start_detection_btn.setMinimumSize(QtCore.QSize(0, 30))
        self.start_detection_btn.setStyleSheet("QPushButton {\n"
"    background-color:rgb(41, 128, 185);\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 10px;\n"
"    border: 2px groove gray;\n"
"    border-style: outset;\n"
"    font: 75 9pt \"Arial\";\n"
"}\n"
"QPushButton:disabled {\n"
"    background-color:gray;\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 7px;\n"
"    border: 2px groove gray;\n"
"    border-style: outset;\n"
"    font: 75 9pt \"Arial\";\n"
"}\n"
"")
        self.start_detection_btn.setCheckable(True)
        self.start_detection_btn.setObjectName("start_detection_btn")
        self.horizontalLayout_10.addWidget(self.start_detection_btn)
        self.verticalLayout_11.addWidget(self.widget_24)
        self.verticalLayout_4.addWidget(self.functional_testing_panel)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_3.addWidget(self.scrollArea)
        self.verticalLayout_3.setStretch(0, 2)
        self.horizontalLayout.addWidget(self.widget_left)
        self.widget_right = QtWidgets.QWidget(Operation)
        self.widget_right.setStyleSheet("background-color: rgb(218, 218, 218);\n"
"border-radius: 5px;")
        self.widget_right.setObjectName("widget_right")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.widget_right)
        self.verticalLayout_6.setContentsMargins(9, 9, 9, 9)
        self.verticalLayout_6.setSpacing(9)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.widget_3 = QtWidgets.QWidget(self.widget_right)
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.widget_3)
        self.verticalLayout_8.setContentsMargins(0, 2, 0, 0)
        self.verticalLayout_8.setSpacing(11)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.widget = QtWidgets.QWidget(self.widget_3)
        self.widget.setStyleSheet("background-color: rgb(236, 240, 241);")
        self.widget.setObjectName("widget")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_language = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_language.setFont(font)
        self.label_language.setStyleSheet("background-color: rgb(255, 255, 255，200);")
        self.label_language.setObjectName("label_language")
        self.horizontalLayout_12.addWidget(self.label_language)
        self.language_selection = QtWidgets.QComboBox(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.language_selection.sizePolicy().hasHeightForWidth())
        self.language_selection.setSizePolicy(sizePolicy)
        self.language_selection.setMinimumSize(QtCore.QSize(0, 25))
        self.language_selection.setStyleSheet("\\\\ color:black;\n"
"\\\\ border:1px solid black;\n"
"\\\\ border-radius: 5px;")
        self.language_selection.setObjectName("language_selection")
        self.language_selection.addItem("")
        self.language_selection.addItem("")
        self.horizontalLayout_12.addWidget(self.language_selection)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem)
        self.log_clear = QtWidgets.QPushButton(self.widget)
        self.log_clear.setMinimumSize(QtCore.QSize(0, 30))
        self.log_clear.setStyleSheet("QPushButton {\n"
"    background-color: rgb(39, 174, 96);\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 7px;\n"
"    border: 2px groove gray;\n"
"    border-style: outset;\n"
"    font: 75 9pt \"Arial\";\n"
"}\n"
"QPushButton:disabled {\n"
"    background-color:gray;\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 7px;\n"
"    border: 2px groove gray;\n"
"    border-style: outset;\n"
"    font: 75 9pt \"Arial\";\n"
"}\n"
"")
        self.log_clear.setObjectName("log_clear")
        self.horizontalLayout_12.addWidget(self.log_clear)
        self.horizontalLayout_12.setStretch(0, 1)
        self.horizontalLayout_12.setStretch(1, 1)
        self.horizontalLayout_12.setStretch(2, 2)
        self.horizontalLayout_12.setStretch(3, 1)
        self.verticalLayout_8.addWidget(self.widget)
        self.loggerLabel = QtWidgets.QTextBrowser(self.widget_3)
        self.loggerLabel.setStyleSheet("background-color: rgb(236, 240, 241);\n"
"border-radius: 5px;")
        self.loggerLabel.setObjectName("loggerLabel")
        self.verticalLayout_8.addWidget(self.loggerLabel)
        self.verticalLayout_8.setStretch(1, 8)
        self.verticalLayout_6.addWidget(self.widget_3)
        self.widget_4 = QtWidgets.QWidget(self.widget_right)
        self.widget_4.setStyleSheet("")
        self.widget_4.setObjectName("widget_4")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.widget_4)
        self.verticalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.widget_11 = QtWidgets.QWidget(self.widget_4)
        self.widget_11.setStyleSheet("background-color: rgb(236, 240, 241);\n"
"border-radius: 5px;")
        self.widget_11.setObjectName("widget_11")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout(self.widget_11)
        self.horizontalLayout_20.setContentsMargins(9, 0, 9, 0)
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setContentsMargins(-1, -1, 11, -1)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.address = QtWidgets.QLabel(self.widget_11)
        self.address.setStyleSheet("font: 10pt \"Arial\";")
        self.address.setObjectName("address")
        self.horizontalLayout_14.addWidget(self.address)
        self.ip_address_edit = QtWidgets.QLineEdit(self.widget_11)
        self.ip_address_edit.setEnabled(True)
        self.ip_address_edit.setMinimumSize(QtCore.QSize(0, 20))
        self.ip_address_edit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.ip_address_edit.setText("")
        self.ip_address_edit.setReadOnly(True)
        self.ip_address_edit.setObjectName("ip_address_edit")
        self.horizontalLayout_14.addWidget(self.ip_address_edit)
        self.horizontalLayout_20.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setContentsMargins(-1, -1, 11, -1)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label = QtWidgets.QLabel(self.widget_11)
        self.label.setStyleSheet("font: 10pt \"Arial\";")
        self.label.setObjectName("label")
        self.horizontalLayout_15.addWidget(self.label)
        self.firmware_version_edit = QtWidgets.QLineEdit(self.widget_11)
        self.firmware_version_edit.setEnabled(True)
        self.firmware_version_edit.setMinimumSize(QtCore.QSize(0, 20))
        self.firmware_version_edit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.firmware_version_edit.setText("")
        self.firmware_version_edit.setReadOnly(True)
        self.firmware_version_edit.setObjectName("firmware_version_edit")
        self.horizontalLayout_15.addWidget(self.firmware_version_edit)
        self.horizontalLayout_20.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_20.setStretch(0, 2)
        self.horizontalLayout_20.setStretch(1, 2)
        self.verticalLayout_14.addWidget(self.widget_11)
        self.widget_18 = QtWidgets.QWidget(self.widget_4)
        self.widget_18.setStyleSheet("background-color: rgb(236, 240, 241);\n"
"border-radius: 5px;")
        self.widget_18.setObjectName("widget_18")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget_18)
        self.gridLayout_2.setContentsMargins(9, 0, 9, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout_32 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_32.setObjectName("horizontalLayout_32")
        self.power_backup = QtWidgets.QLabel(self.widget_18)
        self.power_backup.setStyleSheet("font: 10pt \"Arial\";")
        self.power_backup.setObjectName("power_backup")
        self.horizontalLayout_32.addWidget(self.power_backup)
        self.backup_battery_power = QtWidgets.QLabel(self.widget_18)
        self.backup_battery_power.setStyleSheet("")
        self.backup_battery_power.setObjectName("backup_battery_power")
        self.horizontalLayout_32.addWidget(self.backup_battery_power)
        self.gridLayout_2.addLayout(self.horizontalLayout_32, 1, 1, 1, 1)
        self.horizontalLayout_31 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_31.setObjectName("horizontalLayout_31")
        self.backup_battery_state = QtWidgets.QLabel(self.widget_18)
        self.backup_battery_state.setEnabled(False)
        self.backup_battery_state.setMinimumSize(QtCore.QSize(18, 18))
        self.backup_battery_state.setMaximumSize(QtCore.QSize(18, 18))
        self.backup_battery_state.setStyleSheet("QLabel {\n"
"    background-color:green;\n"
"    border-radius: 9px;\n"
"    border: 1px solid lightgreen;\n"
"}\n"
"QLabel:disabled {\n"
"    border-radius: 9px;\n"
"    background-color:grey;\n"
"    border: 1px solid\n"
"}")
        self.backup_battery_state.setText("")
        self.backup_battery_state.setObjectName("backup_battery_state")
        self.horizontalLayout_31.addWidget(self.backup_battery_state)
        self.backup_battery = QtWidgets.QLabel(self.widget_18)
        self.backup_battery.setStyleSheet("font: 10pt \"Arial\";")
        self.backup_battery.setObjectName("backup_battery")
        self.horizontalLayout_31.addWidget(self.backup_battery)
        self.gridLayout_2.addLayout(self.horizontalLayout_31, 0, 1, 1, 1)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.electricity_name1 = QtWidgets.QLabel(self.widget_18)
        self.electricity_name1.setStyleSheet("font: 10pt \"Arial\";")
        self.electricity_name1.setObjectName("electricity_name1")
        self.horizontalLayout_7.addWidget(self.electricity_name1)
        self.electricity_motor1 = QtWidgets.QLabel(self.widget_18)
        self.electricity_motor1.setObjectName("electricity_motor1")
        self.horizontalLayout_7.addWidget(self.electricity_motor1)
        self.gridLayout_2.addLayout(self.horizontalLayout_7, 1, 2, 1, 1)
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.main_battery_state = QtWidgets.QLabel(self.widget_18)
        self.main_battery_state.setEnabled(False)
        self.main_battery_state.setMinimumSize(QtCore.QSize(18, 18))
        self.main_battery_state.setMaximumSize(QtCore.QSize(18, 18))
        self.main_battery_state.setStyleSheet("QLabel {\n"
"    background-color:green;\n"
"    border-radius: 9px;\n"
"    border: 1px solid lightgreen;\n"
"}\n"
"QLabel:disabled {\n"
"    border-radius: 9px;\n"
"    background-color:grey;\n"
"    border: 1px solid\n"
"}")
        self.main_battery_state.setText("")
        self.main_battery_state.setObjectName("main_battery_state")
        self.horizontalLayout_21.addWidget(self.main_battery_state)
        self.main_battery = QtWidgets.QLabel(self.widget_18)
        self.main_battery.setStyleSheet("font: 10pt \"Arial\";")
        self.main_battery.setObjectName("main_battery")
        self.horizontalLayout_21.addWidget(self.main_battery)
        self.gridLayout_2.addLayout(self.horizontalLayout_21, 0, 0, 1, 1)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.electricity_name_3 = QtWidgets.QLabel(self.widget_18)
        self.electricity_name_3.setStyleSheet("font: 10pt \"Arial\";")
        self.electricity_name_3.setObjectName("electricity_name_3")
        self.horizontalLayout_16.addWidget(self.electricity_name_3)
        self.electricity_motor3 = QtWidgets.QLabel(self.widget_18)
        self.electricity_motor3.setObjectName("electricity_motor3")
        self.horizontalLayout_16.addWidget(self.electricity_motor3)
        self.gridLayout_2.addLayout(self.horizontalLayout_16, 1, 3, 1, 1)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.electricity_name_2 = QtWidgets.QLabel(self.widget_18)
        self.electricity_name_2.setStyleSheet("font: 10pt \"Arial\";")
        self.electricity_name_2.setObjectName("electricity_name_2")
        self.horizontalLayout_11.addWidget(self.electricity_name_2)
        self.electricity_motor2 = QtWidgets.QLabel(self.widget_18)
        self.electricity_motor2.setObjectName("electricity_motor2")
        self.horizontalLayout_11.addWidget(self.electricity_motor2)
        self.gridLayout_2.addLayout(self.horizontalLayout_11, 2, 2, 1, 1)
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.voltage = QtWidgets.QLabel(self.widget_18)
        self.voltage.setStyleSheet("font: 10pt \"Arial\";")
        self.voltage.setObjectName("voltage")
        self.horizontalLayout_23.addWidget(self.voltage)
        self.main_battery_voltage = QtWidgets.QLabel(self.widget_18)
        self.main_battery_voltage.setStyleSheet("")
        self.main_battery_voltage.setObjectName("main_battery_voltage")
        self.horizontalLayout_23.addWidget(self.main_battery_voltage)
        self.gridLayout_2.addLayout(self.horizontalLayout_23, 2, 0, 1, 1)
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.radar_status = QtWidgets.QLabel(self.widget_18)
        self.radar_status.setEnabled(False)
        self.radar_status.setMinimumSize(QtCore.QSize(18, 18))
        self.radar_status.setMaximumSize(QtCore.QSize(18, 18))
        self.radar_status.setStyleSheet("QLabel {\n"
"    background-color:green;\n"
"    border-radius: 9px;\n"
"    border: 1px solid lightgreen;\n"
"}\n"
"QLabel:disabled {\n"
"    border-radius: 9px;\n"
"    background-color:grey;\n"
"    border: 1px solid\n"
"}")
        self.radar_status.setText("")
        self.radar_status.setObjectName("radar_status")
        self.horizontalLayout_24.addWidget(self.radar_status)
        self.radar = QtWidgets.QLabel(self.widget_18)
        self.radar.setStyleSheet("font: 10pt \"Arial\";")
        self.radar.setObjectName("radar")
        self.horizontalLayout_24.addWidget(self.radar)
        self.gridLayout_2.addLayout(self.horizontalLayout_24, 0, 3, 1, 1)
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.electricity_main = QtWidgets.QLabel(self.widget_18)
        self.electricity_main.setStyleSheet("font: 10pt \"Arial\";")
        self.electricity_main.setObjectName("electricity_main")
        self.horizontalLayout_22.addWidget(self.electricity_main)
        self.main_battery_power = QtWidgets.QLabel(self.widget_18)
        self.main_battery_power.setStyleSheet("")
        self.main_battery_power.setObjectName("main_battery_power")
        self.horizontalLayout_22.addWidget(self.main_battery_power)
        self.gridLayout_2.addLayout(self.horizontalLayout_22, 1, 0, 1, 1)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.electricity_name_4 = QtWidgets.QLabel(self.widget_18)
        self.electricity_name_4.setStyleSheet("font: 10pt \"Arial\";")
        self.electricity_name_4.setObjectName("electricity_name_4")
        self.horizontalLayout_18.addWidget(self.electricity_name_4)
        self.electricity_motor4 = QtWidgets.QLabel(self.widget_18)
        self.electricity_motor4.setObjectName("electricity_motor4")
        self.horizontalLayout_18.addWidget(self.electricity_motor4)
        self.gridLayout_2.addLayout(self.horizontalLayout_18, 2, 3, 1, 1)
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.motor_status = QtWidgets.QLabel(self.widget_18)
        self.motor_status.setEnabled(False)
        self.motor_status.setMinimumSize(QtCore.QSize(18, 18))
        self.motor_status.setMaximumSize(QtCore.QSize(18, 18))
        self.motor_status.setStyleSheet("QLabel {\n"
"    background-color:green;\n"
"    border-radius: 9px;\n"
"    border: 1px solid lightgreen;\n"
"}\n"
"QLabel:disabled {\n"
"    border-radius: 9px;\n"
"    background-color:grey;\n"
"    border: 1px solid\n"
"}")
        self.motor_status.setText("")
        self.motor_status.setObjectName("motor_status")
        self.horizontalLayout_25.addWidget(self.motor_status)
        self.motor = QtWidgets.QLabel(self.widget_18)
        self.motor.setStyleSheet("font: 10pt \"Arial\";")
        self.motor.setObjectName("motor")
        self.horizontalLayout_25.addWidget(self.motor)
        self.gridLayout_2.addLayout(self.horizontalLayout_25, 0, 2, 1, 1)
        self.horizontalLayout_33 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_33.setObjectName("horizontalLayout_33")
        self.voltage_backup = QtWidgets.QLabel(self.widget_18)
        self.voltage_backup.setStyleSheet("font: 10pt \"Arial\";")
        self.voltage_backup.setObjectName("voltage_backup")
        self.horizontalLayout_33.addWidget(self.voltage_backup)
        self.backup_battery_voltage = QtWidgets.QLabel(self.widget_18)
        self.backup_battery_voltage.setStyleSheet("")
        self.backup_battery_voltage.setObjectName("backup_battery_voltage")
        self.horizontalLayout_33.addWidget(self.backup_battery_voltage)
        self.gridLayout_2.addLayout(self.horizontalLayout_33, 2, 1, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(0, -1, 0, -1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.camera_3d_status = QtWidgets.QLabel(self.widget_18)
        self.camera_3d_status.setEnabled(False)
        self.camera_3d_status.setMinimumSize(QtCore.QSize(19, 19))
        self.camera_3d_status.setMaximumSize(QtCore.QSize(19, 19))
        self.camera_3d_status.setStyleSheet("QLabel {\n"
"    background-color:green;\n"
"    border-radius: 9px;\n"
"    border: 1px solid lightgreen;\n"
"}\n"
"QLabel:disabled {\n"
"    border-radius: 9px;\n"
"    background-color:grey;\n"
"    border: 1px solid\n"
"}")
        self.camera_3d_status.setText("")
        self.camera_3d_status.setObjectName("camera_3d_status")
        self.horizontalLayout_3.addWidget(self.camera_3d_status)
        self.label_5 = QtWidgets.QLabel(self.widget_18)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_3.addWidget(self.label_5)
        self.gridLayout_2.addLayout(self.horizontalLayout_3, 0, 4, 1, 1)
        self.verticalLayout_14.addWidget(self.widget_18)
        self.verticalLayout_14.setStretch(0, 1)
        self.verticalLayout_14.setStretch(1, 3)
        self.verticalLayout_6.addWidget(self.widget_4)
        self.verticalLayout_6.setStretch(0, 2)
        self.verticalLayout_6.setStretch(1, 1)
        self.horizontalLayout.addWidget(self.widget_right)
        self.horizontalLayout.setStretch(0, 3)
        self.horizontalLayout.setStretch(1, 5)

        self.retranslateUi(Operation)
        QtCore.QMetaObject.connectSlotsByName(Operation)

    def retranslateUi(self, Operation):
        _translate = QtCore.QCoreApplication.translate
        Operation.setWindowTitle(_translate("Operation", "MyAGV"))
        self.label_radar.setText(_translate("Operation", "Laser Radar"))
        self.radar_control_button.setText(_translate("Operation", "ON"))
        self.label_4.setText(_translate("Operation", "3D Camera"))
        self.camera_3d_button.setText(_translate("Operation", "ON"))
        self.basic_control.setText(_translate("Operation", "Basic Control"))
        self.basic_control_selection.setItemText(0, _translate("Operation", "Keyboard Control"))
        self.basic_control_selection.setItemText(1, _translate("Operation", "Joystick-Alphabet"))
        self.basic_control_selection.setItemText(2, _translate("Operation", "Joystick-Number"))
        self.basic_control_button.setText(_translate("Operation", "ON"))
        self.label_3.setText(_translate("Operation", "Map Navigation"))
        self.navigation_selection.setItemText(0, _translate("Operation", "Multi-point Navigation"))
        self.navigation_selection.setItemText(1, _translate("Operation", "Single-point Navigation"))
        self.navigation_2d_button.setText(_translate("Operation", "2D Navigation"))
        self.navigation_3d_button.setText(_translate("Operation", "3D Navigation"))
        self.label_map_nav.setText(_translate("Operation", "Slam Mapping"))
        self.build_map_selection.setItemText(0, _translate("Operation", "GMapping"))
        self.build_map_selection.setItemText(1, _translate("Operation", "Rtabmap"))
        self.open_build_map.setText(_translate("Operation", "Open Build Map"))
        self.save_mapping_button.setText(_translate("Operation", "Save Map"))
        self.label_10.setText(_translate("Operation", "LED Control"))
        self.label_11.setText(_translate("Operation", "HEX"))
        self.label_12.setText(_translate("Operation", "RGB"))
        self.label_luminance.setText(_translate("Operation", "Luminance"))
        self.label_value.setText(_translate("Operation", "value"))
        self.label_2.setText(_translate("Operation", "Functional testing"))
        self.restore_btn.setText(_translate("Operation", "Restore"))
        self.start_detection_btn.setText(_translate("Operation", "Start Detection"))
        self.label_language.setText(_translate("Operation", "Language"))
        self.language_selection.setItemText(0, _translate("Operation", "English"))
        self.language_selection.setItemText(1, _translate("Operation", "Chinese"))
        self.log_clear.setText(_translate("Operation", "Clear Log"))
        self.address.setText(_translate("Operation", "IP Address"))
        self.label.setText(_translate("Operation", "Firmware version"))
        self.power_backup.setText(_translate("Operation", "Power"))
        self.backup_battery_power.setText(_translate("Operation", "0.0"))
        self.backup_battery.setText(_translate("Operation", "Backup Battery"))
        self.electricity_name1.setText(_translate("Operation", "Electricity1"))
        self.electricity_motor1.setText(_translate("Operation", "0.0"))
        self.main_battery.setText(_translate("Operation", "Main Battery"))
        self.electricity_name_3.setText(_translate("Operation", "Electricity3"))
        self.electricity_motor3.setText(_translate("Operation", "0.0"))
        self.electricity_name_2.setText(_translate("Operation", "Electricity2"))
        self.electricity_motor2.setText(_translate("Operation", "0.0"))
        self.voltage.setText(_translate("Operation", "Voltage"))
        self.main_battery_voltage.setText(_translate("Operation", "0.0"))
        self.radar.setText(_translate("Operation", "Radar"))
        self.electricity_main.setText(_translate("Operation", "Power"))
        self.main_battery_power.setText(_translate("Operation", "0.0"))
        self.electricity_name_4.setText(_translate("Operation", "Electricity4"))
        self.electricity_motor4.setText(_translate("Operation", "0.0"))
        self.motor.setText(_translate("Operation", "Motor"))
        self.voltage_backup.setText(_translate("Operation", "Voltage"))
        self.backup_battery_voltage.setText(_translate("Operation", "0.0"))
        self.label_5.setText(_translate("Operation", "3D Camera"))
